### PR TITLE
Creation and Addition of .env file 

### PR DESCRIPTION
**Pull request by Tumii01**

### CODE REVIEW

**Comment by Renzo-codespace** [comment]
@Tumii01 Please update this branch locally with the updates in the main branch and push again.

**Comment by Renzo-codespace** [comment]
You'll have to merge in the new changes from the main branch, first please. 
Please see the section where all the checks are indicated.
I recommend that you do this locally, thought.

**Review by Kenneth-Ngcobo — APPROVED** [review]

**Review by Akido123 — COMMENTED** [review]
Looks Good

**Review by Renzo-codespace — DISMISSED** [review]
Perfect!

**Review by Renzo-codespace — APPROVED** [review]
Well done!
- [x] no connection string in code base
- [x] mongo client instantiated correctly

**Review by NelsonMALGAS — APPROVED** [review]

**Pull request merged**
