### PR TITLE
Fixing the Recipe Card display

### PR DESCRIPTION
**Pull request by Tumii01**
Add new Icons and edited the picture size

### CODE REVIEW

**Review by Matere29 — APPROVED** [review]
Looking good, I like the addition of icons.

**Review by Tshireletso46 — COMMENTED** [review]
The card looks good but it would be more nicer if you reduce the size of the recipe title, currently it looks big.

**Review by kgakatsikeamogetswe — DISMISSED** [review]
Tittle font size is way big, please minimize the size of the tittle and fix the mobile view of the card because everything is huge on the mobile view.

**Review by Kenneth-Ngcobo — DISMISSED** [review]

**Review by Tshireletso46 — DISMISSED** [review]
Looks good, but not responsive

**Review by Kenneth-Ngcobo — APPROVED** [review]
Awesome Tumi & Rorisang, I love this look!

**Review by Matere29 — APPROVED** [review]
Looking good.

**Review by NelsonMALGAS — APPROVED** [review]
Layout looks good

**Review by Tshireletso46 — APPROVED** [review]
The navbar and the cards looks good!

**Pull request merged**
