### PR TITLE
Added Details Component

### PR DESCRIPTION
**Pull request by Akido123**
Added Details Components

### CODE REVIEW

**Review by Kenneth-Ngcobo — DISMISSED** [review]
Keep pull requests lean, only modifying a few files
Don't use inline styling

**Review by chemonique — COMMENTED** [review]
maybe remove the error component

**Review by NelsonMALGAS — APPROVED** [review]
Looking good

**Review by Kenneth-Ngcobo — APPROVED** [review]

**Review by chemonique — APPROVED** [review]
Looks great

**Pull request merged**
