### PR TITLE
Fixing the pre rendering

### PR DESCRIPTION
**Pull request by NelsonMALGAS**
Added pre-rendering & pagination to the home page and also fixed some of the outstanding issues

### CODE REVIEW

**Review by kgakatsikeamogetswe — APPROVED** [review]
I see you cleaned up the code so it's easier to read and understand.

**Review by Kenneth-Ngcobo — CHANGES_REQUESTED** [review]
After clicking next two times, the previous button doesn't load any data.
The pull request has both pre-rendering and load more modifications, limit pull requests to one feature.

**Review by Kenneth-Ngcobo — APPROVED** [review]
Well done! Styling can be improved when show more is clicked, currently the skeleton is squeezed to the side by the Show More button

**Review by kgakatsikeamogetswe — APPROVED** [review]
Everything looks fine! The skeleton styling will be improved in no time. Thank you!

**Pull request merged**
